name: persian_numeric_convertor
description: simple convert to convert Rial number to Toman.
version: 1.0.1
repository: https://github.com/mtkz/persian_numeric_convertor

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
